package domain

import (
	"time"

	"github.com/google/uuid"
	"gorm.io/datatypes"
)

// GuideLine stores work instructions (text, images, URL) for a specific sub-work
type GuideLine struct {
	ID         uuid.UUID      `gorm:"type:uuid;default:gen_random_uuid();primaryKey" json:"id"`
	SubWorkID  uuid.UUID      `gorm:"column:id_sub_work;type:uuid;not null" json:"id_sub_work"`
	GuideText  string         `gorm:"column:guide_text" json:"guide_text"`
	GuideImages datatypes.JSON `gorm:"column:guide_images;type:jsonb;default:'[]'" json:"guide_images"`
	GuideURL   string         `gorm:"column:guide_url" json:"guide_url"`
	CreatedAt  time.Time      `json:"created_at"`
	UpdatedAt  time.Time      `json:"updated_at"`
}

// TableName overrides the default table name generated by gorm
func (GuideLine) TableName() string {
	return "guidelines"
}

// GuideLineRepository defines the interface for guideline data access
type GuideLineRepository interface {
	FindBySubWorkID(subWorkID uuid.UUID) (*GuideLine, error)
	Save(g *GuideLine) error
}
