package domain

import (
	"time"

	"github.com/google/uuid"
	"gorm.io/datatypes"
	"gorm.io/gorm"
)

// Report captures a frozen snapshot definition of a report generated by a Manager.
type Report struct {
	ID        uuid.UUID `gorm:"type:uuid;default:gen_random_uuid();primaryKey" json:"id"`
	AssignID  uuid.UUID `gorm:"column:id_assign;type:uuid;not null;index" json:"id_assign"`
	Assign    *Assign   `gorm:"foreignKey:AssignID;references:ID" json:"assign,omitempty"`

	// Title of the report (e.g. "Báo cáo nghiệm thu lót bạt Phase 1")
	Title     string    `gorm:"type:varchar(255);not null" json:"title"`

	// Type determines the presentation mode (approve vs reject)
	Type      string    `gorm:"type:varchar(50);default:'approve'" json:"type"`

	// ItemKeys stores an array of asset_subwork keys included in the report, or ["all"]
	ItemKeys  datatypes.JSON `gorm:"column:item_keys;type:jsonb;default:'[]'" json:"item_keys"`

	// Conclusion inserted by the manager
	Conclusion string `gorm:"type:text" json:"conclusion"`

	// Creator tracking
	PersonCreatedID *uuid.UUID `gorm:"column:id_person_created;type:uuid" json:"id_person_created,omitempty"`

	// Audit trailing
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
	DeletedAt   gorm.DeletedAt `gorm:"index" json:"deleted_at"`
}

func (Report) TableName() string {
	return "reports"
}

// Ensure the Repository interface is clearly defined
type ReportRepository interface {
	Create(r *Report) error
	FindByID(id uuid.UUID) (*Report, error)
	FindByAssignID(assignID uuid.UUID) ([]Report, error)
	Delete(id uuid.UUID) error
}
