package handlers

import (
	"encoding/json"
	"fmt"
	"net/http"
	"regexp"
	"strings"

	"github.com/gin-gonic/gin"
	"github.com/google/uuid"
	"github.com/phuc/cmms-backend/internal/domain"
	"gorm.io/gorm"
)

type ProjectHandler struct {
	Repo domain.ProjectRepository
	DB   *gorm.DB
}

func NewProjectHandler(repo domain.ProjectRepository) *ProjectHandler {
	return &ProjectHandler{Repo: repo}
}

// NewProjectHandlerWithDB creates a handler with DB access for schema operations
func NewProjectHandlerWithDB(repo domain.ProjectRepository, db *gorm.DB) *ProjectHandler {
	return &ProjectHandler{Repo: repo, DB: db}
}

// toSnakeCase converts a string to snake_case
func toSnakeCase(s string) string {
	s = strings.ToLower(s)
	re := regexp.MustCompile(`[^a-z0-9]+`)
	s = re.ReplaceAllString(s, "_")
	s = strings.Trim(s, "_")
	return s
}

func (h *ProjectHandler) GetAllProjects(c *gin.Context) {
	data, err := h.Repo.GetAllProjects()
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}
	c.JSON(http.StatusOK, data)
}

func (h *ProjectHandler) GetProjectClassifications(c *gin.Context) {
	data, err := h.Repo.GetAllClassifications()
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}
	c.JSON(http.StatusOK, data)
}

func (h *ProjectHandler) GetAllMainCategories(c *gin.Context) {
	data, err := h.Repo.GetAllMainCategories()
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}
	c.JSON(http.StatusOK, data)
}

func (h *ProjectHandler) GetChildCategories(c *gin.Context) {
	paramID := c.Param("id")
	id, err := uuid.Parse(paramID)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": "Invalid ID"})
		return
	}
	data, err := h.Repo.GetChildCategoriesByMainID(id)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}
	c.JSON(http.StatusOK, data)
}

func (h *ProjectHandler) GetProjectByID(c *gin.Context) {
	idStr := c.Param("id")
	id, err := uuid.Parse(idStr)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": "Invalid Project ID"})
		return
	}
	data, err := h.Repo.GetProjectByID(id)
	if err != nil {
		c.JSON(http.StatusNotFound, gin.H{"error": "Project not found"})
		return
	}
	c.JSON(http.StatusOK, data)
}

func (h *ProjectHandler) CreateProject(c *gin.Context) {
	var req domain.Project
	if err := c.ShouldBindJSON(&req); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}
	if req.ProjectName == "" {
		c.JSON(http.StatusBadRequest, gin.H{"error": "Project Name is required"})
		return
	}
	// ID is generated by DB default if using gen_random_uuid(), but GORM usually handles this.
    // If not, we can generate it here:
    if req.ID == uuid.Nil {
        req.ID = uuid.New()
    }

	if err := h.Repo.CreateProject(&req); err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}
	c.JSON(http.StatusCreated, req)
}

func (h *ProjectHandler) UpdateProject(c *gin.Context) {
	idStr := c.Param("id")
	id, err := uuid.Parse(idStr)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": "Invalid Project ID"})
		return
	}

	var req domain.Project
	if err := c.ShouldBindJSON(&req); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}
    
    // Ensure ID matches
    req.ID = id

	if err := h.Repo.UpdateProject(&req); err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}
	c.JSON(http.StatusOK, req)
}

func (h *ProjectHandler) CreateMainCategory(c *gin.Context) {
	var req domain.MainCategory
	if err := c.ShouldBindJSON(&req); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}
	if req.Name == "" {
		c.JSON(http.StatusBadRequest, gin.H{"error": "Name is required"})
		return
	}
	if err := h.Repo.CreateMainCategory(&req); err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}
	c.JSON(http.StatusCreated, req)
}

func (h *ProjectHandler) CreateChildCategory(c *gin.Context) {
	var req domain.ChildCategory
	if err := c.ShouldBindJSON(&req); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}
	if req.Name == "" {
		c.JSON(http.StatusBadRequest, gin.H{"error": "Name is required"})
		return
	}
	// Require either MainCategoryID OR StationID
	if req.MainCategoryID == uuid.Nil && req.StationID == nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": "Either MainCategoryID or StationID is required"})
		return
	}
	
	// Auto-generate column_key from name
	req.ColumnKey = toSnakeCase(req.Name)
	
	// Create child category in DB
	if err := h.Repo.CreateChildCategory(&req); err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}
	
	// Auto-create column in project_characteristics table
	if h.DB != nil && req.ColumnKey != "" {
		sql := fmt.Sprintf(
			"ALTER TABLE project_characteristics ADD COLUMN IF NOT EXISTS %s INTEGER DEFAULT 0",
			req.ColumnKey,
		)
		if err := h.DB.Exec(sql).Error; err != nil {
			// Log but don't fail - column might already exist
			fmt.Printf("Warning: Could not create column %s: %v\n", req.ColumnKey, err)
		}
	}
	
	c.JSON(http.StatusCreated, req)
}

// UpdateChildCategory handles PUT /child-categories/:id
func (h *ProjectHandler) UpdateChildCategory(c *gin.Context) {
	idStr := c.Param("id")
	id, err := uuid.Parse(idStr)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": "Invalid Child Category ID"})
		return
	}
	
	var req struct {
		Name             string  `json:"name"`
		RequiresInverter *bool   `json:"requires_inverter"`
		StationID        *string `json:"station_id"` // Can be null to unlink
	}
	if err := c.ShouldBindJSON(&req); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}
	
	// Update in database
	updates := map[string]interface{}{}
	if req.Name != "" {
		updates["name"] = req.Name
		updates["column_key"] = toSnakeCase(req.Name)
	}
	if req.RequiresInverter != nil {
		updates["requires_inverter"] = *req.RequiresInverter
	}
	// Handle station_id (can be null to unlink, or a UUID string to link)
	if req.StationID != nil {
		if *req.StationID == "" {
			updates["id_station"] = nil
		} else {
			stationUUID, err := uuid.Parse(*req.StationID)
			if err == nil {
				updates["id_station"] = stationUUID
			}
		}
	}
	
	if h.DB != nil {
		if err := h.DB.Model(&domain.ChildCategory{}).Where("id = ?", id).Updates(updates).Error; err != nil {
			c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
			return
		}
	}
	
	c.JSON(http.StatusOK, gin.H{"message": "Child category updated successfully", "id": id})
}

func (h *ProjectHandler) GetChildCategoriesByStationID(c *gin.Context) {
	paramID := c.Param("id")
	id, err := uuid.Parse(paramID)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": "Invalid Station ID"})
		return
	}
	data, err := h.Repo.GetChildCategoriesByStationID(id)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}
	c.JSON(http.StatusOK, data)
}

func (h *ProjectHandler) GetProjectCharacteristics(c *gin.Context) {
	idStr := c.Param("id")
	id, err := uuid.Parse(idStr)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": "Invalid Project ID"})
		return
	}

	data, err := h.Repo.GetProjectCharacteristic(id)
	if err != nil {
		// If not found, we might return a default/empty structure or let the frontend handle it.
		// For now, if error is "record not found" (depending on repo implementation), we might return null or 404.
		// Assuming repo returns error for not found.
		c.JSON(http.StatusNotFound, gin.H{"error": "Characteristics not found", "details": err.Error()})
		return
	}
	c.JSON(http.StatusOK, data)
}

func (h *ProjectHandler) UpdateProjectCharacteristics(c *gin.Context) {
	idStr := c.Param("id")
	id, err := uuid.Parse(idStr)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": "Invalid Project ID"})
		return
	}

	// Accept flexible map from frontend
	var req map[string]interface{}
	if err := c.ShouldBindJSON(&req); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}

	// Get existing or create new record
	existing, _ := h.Repo.GetProjectCharacteristic(id)
	if existing == nil {
		existing = &domain.ProjectCharacteristic{
			ProjectID: id,
		}
	}

	// Parse existing ChildCategoryData
	existingData := make(map[string]interface{})
	if existing.ChildCategoryData != nil {
		json.Unmarshal(existing.ChildCategoryData, &existingData)
	}

	// Merge new data into existing
	for key, value := range req {
		switch key {
		case "inverter_sub_area_count":
			if v, ok := value.(float64); ok {
				existing.InverterSubAreaCount = int(v)
			}
		case "inverter":
			if v, ok := value.(float64); ok {
				existing.Inverter = int(v)
			}
		case "inverter_details":
			if bytes, err := json.Marshal(value); err == nil {
				existing.InverterDetails = bytes
			}
		default:
			// All other keys (process_ids, area_name, quantities) go into child_category_data JSON
			existingData[key] = value
		}
	}

	// Marshal back to JSON
	if dataBytes, err := json.Marshal(existingData); err == nil {
		existing.ChildCategoryData = dataBytes
	}

	if err := h.Repo.UpdateProjectCharacteristic(id, existing); err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}
	c.JSON(http.StatusOK, existing)
}

func (h *ProjectHandler) DeleteProject(c *gin.Context) {
	idStr := c.Param("id")
	id, err := uuid.Parse(idStr)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": "Invalid Project ID"})
		return
	}
	if err := h.Repo.DeleteProject(id); err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}
	c.JSON(http.StatusOK, gin.H{"message": "Project deleted successfully"})
}

func (h *ProjectHandler) DeleteMainCategory(c *gin.Context) {
	idStr := c.Param("id")
	id, err := uuid.Parse(idStr)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": "Invalid Main Category ID"})
		return
	}
	if err := h.Repo.DeleteMainCategory(id); err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}
	c.JSON(http.StatusOK, gin.H{"message": "Main category deleted successfully"})
}

func (h *ProjectHandler) DeleteChildCategory(c *gin.Context) {
	idStr := c.Param("id")
	id, err := uuid.Parse(idStr)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": "Invalid Child Category ID"})
		return
	}
	if err := h.Repo.DeleteChildCategory(id); err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}
	c.JSON(http.StatusOK, gin.H{"message": "Child category deleted successfully"})
}
