input {
  # Accept JSON logs over TCP from Docker/Filebeat
  tcp {
    port => 2508
    codec => json
  }
}

filter {
  # Attempt to parse json if it comes as a string in 'message'
  if [message] =~ /^\{.*/ {
    json {
      source => "message"
    }
  }

  mutate {
    add_field => { "environment" => "development" }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "cmms-backend-logs-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}
